language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: hVX2jU6YmF2Z9hM9PPN6kaLUyIo30C5TD0mG9Kgd20KpVbxr1Yy4r7YF4GmK3MTInfsAHukgU21poDIOViLrY+dbYL1h5axndfUzqR7rEpqBOHGon56BWa0Roir43LsAthoEm4lfgk2192oDY83m84GTdZaWP3OXwkO9C+HJOCZnhYyaVEBU0W7LGxdIGEkrfJaPYFQVXFqNeNnS6hh1DcgpdQTQvEVTExLSu8b2XRK8k/dAKt/Bn2+/nZRB/ZZdU+QGYAJMVGdkxuQGfPbSHyPDVtIt8TyWDPHWWVTpKlgGybMxN6CacZxSie/NWOMfZ1OkkfsohiADgz/p6Pp9M4VmNicZQmrvLoMfLQh1RyeUDM7Prvw9ycaSPb8RpLbw0a0c25bqhx2JM6XgMghHmwp1eF5VeyOoZFlRlenmbZ8fFI7a92UAxOewaKISs4t/w1Bgp3Oz3L6XglHVp1bZQmwP1lTS7SXIUIRaNn3Mf4quDTV7/2fiJmFPDXqE34Uejo+EHGnyaDyWP/oKXRsQ1tPzuPtudgWcIejmSsVnpHNO6QxwzoqjswEJAQpz7oin+1+0oGPpat3AbF7148+mgnn3KirzEHG6lp/G7sF3lpCPTTlkdbAR2JWbfr1yZQpzeCsNxUoHgb6ftwMwT+eOVnXYvRnaeng/uiw5LymjWJk=
